name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  compile:
    runs-on: Agent-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          # adjust version as per your Jenkins setup
      - name: Frontend Compilation (Syntax Check)
        run: |
          cd client
          find . -name "*.js" -exec node --check {} +

gitleaks_scan:
    runs-on: Agent-1
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Gitleaks Setup
        uses: gitleaks/gitleaks-action@v1
        
      - name: Run Gitleaks Scan
        run: |
          gitleaks detect --source ./api --exit-code 1
          gitleaks detect --source ./client --exit-code 1
          
